pipeline:
  publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: drone:5000/cicd_helloworld
    registry: drone:5000
    tags: latest
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: http://master:8001
    kubernetes_token: 6323d4.d85d129e07132217
    namespace: default
    deployment: demo-app-cicd
    repo: drone:5000/cicd_helloworld
    registry: drone:5000
    tag: latest
