pipeline:
  publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: drone:5000/cicd_helloworld
    registry: drone:5000
    insecure: true
    tags: latest
  deploy:
    image:  devnetsandbox/kube
    kubernetes_server: http://master:8001
    kubernetes_token: 6323d4.d85d129e07132217
    namespace: default
    deployment: demo-app-cicd
    container: cicd-helloworld
    repo: drone:drone:5000/cicd-helloworld
    registry: drone:5000
    insecure: true
    tag: latest
