pipeline:
  build:
    image: golang
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main
  publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: drone:5000/cicd-helloworld
    registry: drone:5000
    insecure: true
    tags: latest
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: http://10.10.20.1:8001
    kubernetes_token: 6323d4.d85d129e07132217
    namespace: default
    deployment: demo-app-cicd
    container: cicd-helloworld
    repo: drone:5000/cicd-helloworld
    registry: drone:5000
    insecure: true
    tag: latest
